### ISSUE TITLE
My life

### ISSUE THREAD

**Issue by DominikSoltysiak** [DominikSoltysiak/WebProjekt#1]
So i have an issue with my life lol uwu,
so thats why i am gonna end my life.

Yours Solty

**Comment by niklasgruebl** [comment]
so sad!
can we get 50 likes?

**Comment by DominikSoltysiak** [comment]
nah

**Comment by niklasgruebl** [comment]
thats even sadder

**Comment by DominikSoltysiak** [comment]
Well fuck me then bruh

**Comment by niklasgruebl** [comment]
bruuuuuuuuuuuuuuuuuuuuuuuuuuuhhhhhhhhhhhhhhhhhhhhhhh

**Comment by joachimPelzederHTL** [comment]
Buuu r g er

**Comment by niklasgruebl** [comment]
hamburger
